Repository alyu201/Reactalk, pull requests merged in 2022-09, with the labels that each got.

#37 Feature/system commands #3
  src/commandProcessor/invalidCommandException.ts
  src/commandProcessor/processors/system/app/create.ts
  src/commandProcessor/processors/system/editor/next.ts
  src/commandProcessor/processors/system/editor/previous.ts
  src/commandProcessor/processors/system/file/new.ts
  src/commandProcessor/processors/system/terminal/browse.ts
  src/commandProcessor/processors/system/terminal/toggle.ts
  src/commandProcessor/processors/systemProcessor.ts
  src/definitions/commandPrefixes.ts
  src/inputProcessor/speechRecognition.ts
Labels: enhancement, feature

#39 Feature/editing commands #3
  src/commandProcessor/commandProcessor.ts
  src/commandProcessor/processors/editing/backspace.ts
  src/commandProcessor/processors/editing/copy.ts
  src/commandProcessor/processors/editing/delete.ts
  src/commandProcessor/processors/editing/skip.ts
  src/definitions/commandPrefixes.ts
Labels: feature

#35 Feature/navigation commands #3
  src/commandProcessor/commandProcessor.ts
  src/commandProcessor/processors/navigation/enter.ts
  src/commandProcessor/processors/navigation/focus.ts
  src/commandProcessor/processors/navigation/go.ts
  src/commandProcessor/processors/navigation/goDown.ts
  src/commandProcessor/processors/navigation/goLeft.ts
  src/commandProcessor/processors/navigation/goRight.ts
  src/commandProcessor/processors/navigation/goToFunction.ts
  src/commandProcessor/processors/navigation/goUp.ts
  src/commandProcessor/processors/navigation/navigationUtility.ts
  src/commandProcessor/processors/navigation/selectFromHereToLine.ts
  src/commandProcessor/processors/navigation/selectLine.ts
  src/definitions/commandPrefixes.ts
Labels: enhancement, feature

#33 Feature/composition commands #4
  src/commandProcessor/processors/compositionProcessor.ts
  src/commandProcessor/processors/system/file/new.ts
  src/commandProcessor/processors/system/file/remove.ts
  src/definitions/codeSnippets.json
  src/definitions/commandPrefixes.ts
Labels: enhancement, feature, in progress

#41 Feature/navigation commands
  src/commandProcessor/commandProcessor.ts
  src/commandProcessor/processors/navigation/goUp.ts
Labels: enhancement

#43 Composition & editing command fixes
  src/commandProcessor/processors/compositionProcessor.ts
  src/commandProcessor/processors/editing/confirm.ts
  src/commandProcessor/utility.ts
  src/definitions/codeSnippets.json
  src/definitions/commandPrefixes.ts
Labels: enhancement, feature

#27 Extension configuration and setup
  package.json
  resources/comment-code.svg
  resources/dark/microphone.svg
  resources/light/microphone.svg
  resources/paused.svg
  resources/started.svg
  resources/stopped.svg
  src/commandProcessor/processors/system/application/start.ts
  src/commandProcessor/processors/system/application/stop.ts
  src/commandProcessor/processors/system/listening/pause.ts
  src/commandProcessor/processors/system/listening/start.ts
  src/commandProcessor/processors/system/listening/stop.ts
  src/commandProcessor/providers/commandProvider.ts
  src/commandProcessor/providers/controlProvider.ts
  src/commandProcessor/providers/symbolsProvider.ts
  src/definitions/commands.json
  src/definitions/status.ts
  src/extension.ts
  src/inputProcessor/inputProcessor.ts
  src/inputProcessor/speechRecognition.ts
Labels: enhancement, feature, in progress

#46 Feature/system commands
  src/commandProcessor/processors/system/folder/collapse.ts
  src/commandProcessor/processors/system/folder/open.ts
  src/definitions/commandPrefixes.ts
Labels: enhancement, feature

#47 Feature/navigation commands
  src/commandProcessor/commandProcessor.ts
  src/commandProcessor/processors/navigation/focus.ts
  src/commandProcessor/processors/navigation/go.ts
  src/commandProcessor/processors/navigation/goDown.ts
  src/commandProcessor/processors/navigation/goLeft.ts
  src/commandProcessor/processors/navigation/goRight.ts
  src/commandProcessor/processors/navigation/goToLine.ts
  src/commandProcessor/processors/navigation/goUp.ts
  src/commandProcessor/processors/navigation/scroll.ts
  src/commandProcessor/processors/navigation/selectFromHereToLine.ts
  src/commandProcessor/processors/navigationProcessor.ts
  src/commandProcessor/processors/system/file/open.ts
  src/definitions/commandPrefixes.ts
Labels: enhancement, feature

#51 Add missing commands and symbols
  src/definitions/commands.json
  src/definitions/symbols.ts
Labels: documentation, enhancement
